import type { Metadata } from "next";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import { Header } from "@/components/molecules/Header";
import { Footer } from "@/components/molecules/Footer";

export const metadata: Metadata = {
  title: "Get Help with Your Debt | UK Debt Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
      <GoogleTagManager gtmId="AW-17688499544" />
    </html>
  );
}
